version: '3.8'

services:
  redis-cetus:
    image: redis:latest
    container_name: redis-cetus
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
    driver: local